js/gated-content/src/components/LiveStreamListing.vue, js/gated-content/src/components/VideoListing.vue, modules/openy_gc_storage/openy_gc_storage.install, openy_gated_content.permissions.yml, openy_gated_content.services.yml, src/EventSubscriber/GatedContentSubscriber.php
Task - https://fivejars.atlassian.net/browse/VYMCA-19
=> [VYMCA-19] Close access to video, live stream pages

js/gated-content/src/components/MediaPlayer.vue, src/Plugin/video_embed_field/Provider/VimeoEvent.php
**Note:** the event will work correctly if the domain in a whitelist, for now, here only **rose.openy.docksal**, I will add build domain when it will be ready. If on local you use something except for **rose.openy.docksal**, ping me and I will add your domain too
Note: video iframe size will be fixed later
=> [VYMCA-36] Add support of Vimeo live streams

modules/openy_gc_storage/openy_gc_storage.module
=> [VYMCA-77] Display compatible video host sources in video field widget

modules/openy_gc_storage/config/install/recurring_events.eventseries.config.yml, modules/openy_gc_storage/openy_gc_storage.install
Fixes https://github.com/ymcatwincities/openy_gated_content/issues/38.
Two major changes are:
- interval: changed to 15 min.
- start time: changed to 4AM based on data from the Y-USA national db. That's the earliest open time of any YMCA branch.
=> Add recurring events series config and update hook.

modules/openy_gc_storage/config/install/core.entity_view_display.eventinstance.live_stream.default.yml, modules/openy_gc_storage/config/install/core.entity_view_display.eventinstance.virtual_meeting.default.yml, modules/openy_gc_storage/openy_gc_storage.install
Jira: https://fivejars.atlassian.net/browse/VYMCA-101
Basecamp: https://3.basecamp.com/3608022/buckets/17045978/todos/3164273439
Github: https://github.com/ymcatwincities/openy_gated_content/issues/53
**Details:**  
Field Inheritance throws an error in JSON API for multiple entity reference fields, because of this we used a different formatter, it works in JSON API but throws an error on the entity view page. To fix this we deleted this field from the output because the entity view page can be used only by admins and the edit form more useful to check all data.
**Steps for review**
=> [VYMCA-101] Hide category field on event view display due to an error

modules/openy_gc_auth/modules/openy_gc_auth_custom/README.md, modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Form/VirtualYCustomLoginForm.php, modules/openy_gc_auth/src/GCUserAuthorizer.php
=> Security issue fix for custom auth provider

modules/openy_gc_auth/modules/openy_gc_auth_daxko_barcode/src/Controller/DaxkoBarcodeController.php
All of the [default messages](https://github.com/fivejars/openy_gated_content/blob/master/modules/openy_gc_auth/modules/openy_gc_auth_daxko_barcode/config/install/openy_gc_auth.provider.daxko_barcode.yml) have a period at the end, so this period between the two strings is causing duplication. Let's get rid of it.
=> Remove extra period from Daxko Barcode Provider

modules/openy_gc_auth/modules/openy_gc_auth_daxko_barcode/src/Form/VirtualYDaxkoBarcodeLoginForm.php
Hi Team,
This pull request is for [https://github.com/ymcatwincities/openy_gated_content/issues/66]()
Please find the test steps below:
- Enable the Daxko barcode module.
- Navigate to GC Auth Settings from menu. **Menu Path:** Manage >> Virtual YMCA Settings >> Auth Settings.
- Edit the Daxkobar code settings.
- Update the Form Label and Form Description.
- Save and Logout.
- Verify the Form label and description.
=> Modifications on form label for having daxko barcode config values.

openy_gated_content.services.yml, src/EditUserAccountAccessCheck.php, src/EventSubscriber/RouteSubscriber.php
https://fivejars.atlassian.net/browse/VYMCA-108
https://3.basecamp.com/3608022/buckets/17045978/todos/3262514567
=> [VYMCA-108] Disable /user/{id}/edit page for virtual y users

modules/openy_gc_auth/modules/openy_gc_auth_reclique/openy_gc_auth_reclique.services.yml, modules/openy_gc_auth/modules/openy_gc_auth_reclique/src/RecliqueClientService.php
https://github.com/ymcatwincities/openy_gated_content/issues/84
- Enable the "Open Y Virtual YMCA Auth ReClique" module for a site using ReClique CORE crm (http://northpennymca-azure-stage.y.org/)
- Configure the module with API user credentials, and use the default Staging endpoint from Reclique
- Attempt member login using any email address - for this repro a legit member email is not required.
=> Fix reclique logger

modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/src/Controller/DaxkoLinkController.php
We have a bug when the user is always redirected to the operations.daxko.com
In this case we cant use train credentials.
I've added logic that fixes it.
=> Train credentials at Daxko

modules/openy_gc_auth/modules/openy_gc_auth_yusa/README.md, modules/openy_gc_auth/modules/openy_gc_auth_yusa/config/install/openy_gc_auth.provider.yusa.yml
No issue, discussed in Slack/email.
- It's possible that sites might be testing, so it may not make sense to provide an upgrade path in this case. Most user should not have enabled this module yet, so we should be good just changing the default.
=> Update YUSA provider config and readme.

modules/openy_gc_auth/modules/openy_gc_auth_custom/README.md, modules/openy_gc_auth/modules/openy_gc_auth_custom/config/install/openy_gc_auth.provider.custom.yml, modules/openy_gc_auth/modules/openy_gc_auth_custom/openy_gc_auth_custom.install, modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Controller/UserController.php, modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Form/VirtualYCustomLoginForm.php, modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Plugin/GCIdentityProvider/Custom.php
https://fivejars.atlassian.net/browse/VYMCA-114
=> [VYMCA-114] Add require_email_verification setting

modules/openy_gc_demo/openy_gc_demo.info.yml
Dependency to openy_gc_auth_custom is not needed for Demo content. It usually blocks or makes it tricky to run demo content migration without a prepared custom authentication method (you have to setup private storage first).
In most cases, we have to import demo content right after Virtual Y installation.
team in Slack
=> Deleted openy_gc_auth_example dependency

modules/openy_gc_auth/modules/openy_gc_auth_yusa/src/Plugin/GCIdentityProvider/YUSA.php
=> Association number field validation applied

modules/openy_gc_autologout/openy_gc_autologout.module
Resolves https://github.com/ymcatwincities/openy_gated_content/issues/95
team in Slack
=> Use range instead of limit for autologout cron

modules/openy_gc_log/src/LogArchiver.php
https://github.com/ymcatwincities/openy_gated_content/issues/102
https://openy.atlassian.net/browse/PRODDEV-188
- [X ] This change does not contain front-end fixes.
team in Slack
=> [PRODDEV-188] Fix Activity Log export if user is null

modules/openy_gc_auth/modules/openy_gc_auth_custom/README.md, modules/openy_gc_auth/modules/openy_gc_auth_custom/config/install/migrate_plus.migration.gc_auth_custom_users.yml, modules/openy_gc_auth/modules/openy_gc_auth_custom/config/install/openy_gc_auth.provider.custom.yml, modules/openy_gc_auth/modules/openy_gc_auth_custom/openy_gc_auth_custom.install, modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Plugin/GCIdentityProvider/Custom.php, modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Plugin/migrate/process/SkipRowIfEmailExcluded.php
- https://fivejars.atlassian.net/browse/VYMCA-115
- https://openy.atlassian.net/browse/PRODDEV-178
Some Y's are having issues with giving admin access to the staff members that exist in the CSV file.
**Steps to reproduce:**
- Run import
- Edit any imported user and assign a "virtual editor" role
- Run import one more time
- Check that user without a "virtual editor" role
**Solution:**
Add settings with the user's emails list that should be skipped during migration.
```csv
Member ID,Member First Name,Primary Member,Member Email,Package Name,Package Site
309302,Test,Yes,TEST@GMAIL.COM,OLY - Family - Staff,Oscar Lasko Branch
309303,Jon,No,JON@GMAIL.COM,OLY - Family - Staff,Oscar Lasko Branch
117892,Doe,Yes,Doe@GMAIL.COM,West Chester - SilverSneakers - S & PP,West …
```
=> [VYMCA-115] Admin accounts for CSV import

modules/openy_gc_auth/modules/openy_gc_auth_personify/src/Controller/PersonifyAuthController.php
Cancelled and Expired Virtual YMCA members were gaining access to Virtual Y sites that use Personify.  Fixes in auth() and userHasActiveMembership() address that problem.
Related Issue/Ticket: https://github.com/ymcatwincities/openy_gated_content/issues/114
team in Slack
=> Update PersonifyAuthController.php to not grant access to Cancelled/Expired members

src/Plugin/Field/FieldWidget/GatedContentPermissionsFieldWidget.php
Jira - https://openy.atlassian.net/browse/PRODDEV-239
Origin issue - https://github.com/ymcatwincities/openy_gated_content/issues/110
New issue after the previous fix:
team in Slack
=> [PRODDEV-239] Fix field_vy_permission widget condition for non-VY content types

composer.json
- https://openy.atlassian.net/browse/PRODDEV-230
- https://fivejars.atlassian.net/browse/VYMCA-134
Was used the patch from this issue - https://www.drupal.org/project/recurring_events/issues/3178669
team in Slack
=> [VYMCA-134] Publishing Series Workflow Should Be Reflected in Instances

composer.json
Error in migration:
```
[error]  DateTimeZone::__construct(): Unknown or bad timezone () (/var/www/docroot/modules/contrib/recurring_events/src/Plugin/migrate/destination/EntityEventSeries.php:69) 
```
This related to the `2.0.0-beta3` version of recurring events, that was released `24 February 2021` - https://www.drupal.org/project/recurring_events/releases/2.0.0-beta3
A related issue that broke our builds - https://www.drupal.org/project/recurring_events/issues/3196428
=> [hotfix] Use tested recurring_events version

modules/openy_gc_demo/openy_gc_demo.info.yml
https://openy.atlassian.net/browse/PRODDEV-243
```
Error: Call to a member function getEnabledBehaviorPlugins() on null in Drupal\paragraphs\ParagraphViewBuilder->buildMultiple() (line 37 of /var/www/docroot/modules/contrib/paragraphs/src/ParagraphViewBuilder.php) 
```
On the drupal 9 demo, we have this error because the banner module disabled
team in Slack
=> [PRODDEV-243] Add missed dependencies

modules/openy_gc_auth/modules/openy_gc_auth_personify/openy_gc_auth_personify.services.yml, modules/openy_gc_auth/modules/openy_gc_auth_personify/src/Client.php, modules/openy_gc_auth/modules/openy_gc_auth_personify/src/Controller/PersonifyAuthController.php, modules/openy_gc_auth/modules/openy_gc_auth_personify/src/EventSubscriber/PersonifyUserLogoutSubscriber.php, modules/openy_gc_auth/modules/openy_gc_auth_personify/src/LogoutClient.php
Canceled and Expired Virtual YMCA members were gaining access to Virtual Y sites that use Personify.  Fixes in auth() and userHasActiveMembership() address that problem.
Related Issue/Ticket: https://github.com/ymcatwincities/openy_gated_content/issues/114
Cherry-picked from https://github.com/fivejars/openy_gated_content/pull/271
team in Slack
=> Update PersonifyAuthController.php to not grant access to Cancelled/Expired members (master)

modules/openy_gc_log/config/install/views.view.virtual_y_logs.yml, modules/openy_gc_log/openy_gc_log.api.php, modules/openy_gc_log/openy_gc_log.install, modules/openy_gc_log/openy_gc_log.views.inc, modules/openy_gc_log/src/LogArchiver.php, modules/openy_gc_log/src/Plugin/views/field/GCLogDayField.php, modules/openy_gc_log/src/Plugin/views/field/GCLogDurationField.php
https://openy.atlassian.net/browse/PRODDEV-187
- Front-end fixes should be tested against all of the Open Y Themes.
team in Slack
=> [PRODDEV-187] Group activity logs by day for user

modules/openy_gc_shared_content/src/SharedContentSourceTypeBase.php
Fix for https://github.com/fivejars/openy_gated_content/pull/287/files#diff-30bce3358885c1e6f9f8561df51ccb508a29a5045346116d778fb071571ac073R179
team in Slack
=> [PRODDEV-229] Fix referer header for shared content

composer.json, modules/openy_gc_search/README.md, modules/openy_gc_search/openy_gc_search.info.yml, modules/openy_gc_search/openy_gc_search.install, modules/openy_gc_search/openy_gc_search.module
https://fivejars.atlassian.net/browse/VYMCA-116
team in Slack
=> [VYMCA-116] Provide search functionality

modules/openy_gc_auth/modules/openy_gc_auth_reclique/src/EventSubscriber/GCAuthReCliqueUserLoginSubscriber.php
**Related Issue/Ticket:** https://github.com/ymcatwincities/openy_gated_content/issues/122
https://github.com/ymcatwincities/openy_gated_content/issues/122
- Go to https://northpennymca-azure-stage.y.org (or equivalent Virtual Y site that uses ReClique CORE crm).
- Verify there are no Permission Mappings present in the Reclique authentication provider configuration.
- Create a new user in the system by logging in with an member's email address for that that is not already in the system
- example used for North Penn: nan_dec@yahoo.com. (Delete this user from Virtual Y site if already present)
- If this user is already present in People, delete that user from People to …
=> ReClique: Default role to Virtual YMCA if no mapping (to master)

modules/openy_gc_log/openy_gc_log.module, modules/openy_gc_log/src/LogArchiver.php
PRODDEV-263
Additional change in this PR is related to
`if (!isset($start) && !isset($end)) {
$query->range(0, self::WORKER_CHUNK_SIZE);
}`
This code was not reachable, so I changed the way this limit works by introducing new function _setWorkerChunkSize_ which is called from cron handler.
team in Slack
=> Fix duplicate logs in export files

modules/openy_gc_auth/modules/openy_gc_auth_yusa/src/Form/VirtualYUSALoginForm.php
Wrap the call to create a new user in sites using Y-USA Provider in a try...catch so the current unhandled exception returned when there is a mismatch between NWM and Daxko when a barcode is entered, and Virtual Y attempts to create a new user for a new barcode.
https://github.com/ymcatwincities/openy_gated_content/issues/132
team in Slack
=> Wrap the call to create a new Y-USA Provider user in a try...catch

modules/openy_gc_log/config/install/views.view.virtual_y_logs.yml, modules/openy_gc_log/openy_gc_log.api.php, modules/openy_gc_log/openy_gc_log.install, modules/openy_gc_log/src/LogArchiver.php
https://openy.atlassian.net/browse/PRODDEV-271
team in Slack
=> [PRODDEV-271] Make logs headers and content more human readable

openy_gated_content.module
https://github.com/ymcatwincities/openy_gated_content/issues/135
=> Cloning issue with Event series and Event instances.

modules/openy_gc_auth/modules/openy_gc_auth_custom/openy_gc_auth_custom.install, modules/openy_gc_personal_training/openy_gc_personal_training.install
`_update_user_permissions` function declared in two modules:  `openy_gc_auth_custom ` and `openy_gc_personal_training`. In case both modules enabled, we will get fatal error.
team in Slack
=> Fix duplicated function name

modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_menu_link_main.yml
https://openy.atlassian.net/browse/PRODDEV-266
team in Slack
=> [PRODDEV-266] Fix menu items migration

modules/openy_gc_shared_content_server/src/Controller/DownloadsIncrementController.php, src/EventSubscriber/GatedContentSubscriber.php
https://openy.atlassian.net/browse/PRODDEV-350
This is just proof of the concept of a possible issue. We have some clients that have empty results from the shared content server, looks like this can be fixed by re-creating the shared server entity and cache clear, so I think this is a more caching issue.
During the investigation, I found a possible problem - https://www.drupal.org/project/jsonapi/issues/2962986
> Actually, what it looks like is happening is if I make a request as an anonymous user, the empty response is being cached. Then all requests afterwards, even using authentication methods, come back with the same empty response (until I clear the cache).
In shared content, all requests goes from anonymous users, so request for the un-approved client can …
=> [PRODDEV-350] Add cache context for anonymous users if we have x-shared-referer header

src/Controller/EventsController.php
[PRODDEV-413](https://openy.atlassian.net/browse/PRODDEV-413?atlOrigin=eyJpIjoiZGMyZmYzNTBhNTI4NDgyYWIyNGE4NDc2ZGFkMDRjMjIiLCJwIjoiamlyYS1zbGFjay1pbnQifQ)
team in Slack
=> [PRODDEV-413] Set the event time zone to UTC

modules/openy_gc_log/src/LogArchiver.php
Fix for [Issue#152](https://github.com/ymcatwincities/openy_gated_content/issues/152)
- Login into VY site as admin or user which has access to VY logs and archives
- From the admin menu, go to Virtual Y --> Logs --> Export log records.
- Click on "Create an export file" button in the page.
- Next from admin menu go to, Virtual Y --> Logs --> Log Archives
- Download and extract latest vy log archive file.
- Open the csv file and content titles are now being displayed.
=> Fix for empty content title issue on exported csv logs.

openy_gated_content.install
https://github.com/ymcatwincities/openy_gated_content/issues/157
https://openy.atlassian.net/browse/PRODDEV-450
team in Slack
=> [PRODDEV-450] Fix the error on a fields definitions' update

modules/openy_gc_storage/openy_gc_storage.install, modules/openy_gc_storage/openy_gc_storage.post_update.php, openy_gated_content.links.menu.yml, openy_gated_content.module, openy_gated_content.routing.yml, src/Form/RebuildDurationsForm.php
[PRODDEV-439](https://openy.atlassian.net/browse/PRODDEV-439)
team in Slack
=> [PRODDEV-439] Add hook_update to update existed data and add duration reference

modules/openy_gc_auth/modules/openy_gc_auth_reclique_sso/README.md, modules/openy_gc_auth/modules/openy_gc_auth_reclique_sso/src/SSOClient.php, modules/openy_gc_auth/src/GCUserAuthorizer.php
https://openy.atlassian.net/browse/PRODDEV-365
team in Slack
=> [PRODDEV-365] ReClique SSO and others improvements

modules/openy_gc_log/src/LogArchiver.php
Backport: https://github.com/ymcatwincities/openy_gated_content/pull/167
See https://openy.slack.com/archives/C6G4ZTLVC/p1635429557024700
team in Slack
=> fix: Use Interface, not child Class in order to support other services

composer.json
Via https://www.drupal.org/project/drupal/issues/3138528
**Related Issue/Ticket:** 
https://openy.atlassian.net/browse/PRODDEV-484
team in Slack
=> [PRODDEV-484] Add patch to resolve indexing error

assets/css/admin_ui_styles.css, composer.json, modules/openy_gc_shared_content/src/Controller/PreviewController.php, modules/openy_gc_shared_content/src/Form/SharedContentFetchForm.php, modules/openy_gc_shared_content/src/Form/SharedContentPreviewForm.php, modules/openy_gc_shared_content/src/Plugin/SharedContentSourceType/VirtualYBlogPost.php, modules/openy_gc_shared_content/src/Plugin/SharedContentSourceType/VirtualYVideo.php, modules/openy_gc_shared_content/src/SharedContentSourceTypeBase.php
https://openy.atlassian.net/browse/PRODDEV-479
https://openy.atlassian.net/browse/PRODDEV-480
You will need to have a site connected to a shared content server in order to test and have the shared content server all configured.
Check out this video: 
https://user-images.githubusercontent.com/238201/145146512-354e3c73-8feb-47c8-98cc-c45ae9312ccd.mp4
- Front end fixes should be tested against all of the Open Y …
=> [PRODDEV-479] [PRODDEV-480]  Flag new shared content

composer.json
Fix-of: https://github.com/ymcatwincities/openy_gated_content/commit/0d4e4d28fec65da7c2e10794501cd7b9ae41ff8a
Addresses: Can't install VIrtual Y on Open Y 9.x-2.x ( sandboxes )
- Front end fixes should be tested against …
=> fix!: Allow installation on Virtual Y on dev Open Y branches

modules/openy_gc_shared_content/openy_gc_shared_content.routing.yml, modules/openy_gc_shared_content/src/Controller/SharedContentController.php, modules/openy_gc_shared_content_server/migrations/migrate_plus.migration.virtual_y_shared_file_blog.yml, modules/openy_gc_shared_content_server/migrations/migrate_plus.migration.virtual_y_shared_file_video.yml, modules/openy_gc_shared_content_server/migrations/migrate_plus.migration.virtual_y_shared_gc_category.yml, modules/openy_gc_shared_content_server/migrations/migrate_plus.migration.virtual_y_shared_gc_category_blog.yml, modules/openy_gc_shared_content_server/migrations/migrate_plus.migration.virtual_y_shared_gc_equipment.yml, modules/openy_gc_shared_content_server/migrations/migrate_plus.migration.virtual_y_shared_gc_level.yml, modules/openy_gc_shared_content_server/migrations/migrate_plus.migration.virtual_y_shared_media_blog_image.yml, modules/openy_gc_shared_content_server/migrations/migrate_plus.migration.virtual_y_shared_media_video.yml, modules/openy_gc_shared_content_server/migrations/migrate_plus.migration.virtual_y_shared_media_video_image.yml, modules/openy_gc_shared_content_server/migrations/migrate_plus.migration.virtual_y_shared_node_blog.yml, modules/openy_gc_shared_content_server/migrations/migrate_plus.migration.virtual_y_shared_node_video.yml, modules/openy_gc_shared_content_server/openy_gc_shared_content_server.info.yml, modules/openy_gc_shared_content_server/openy_gc_shared_content_server.install, modules/openy_gc_shared_content_server/src/Entity/SharedContentSource.php, modules/openy_gc_shared_content_server/src/Form/SharedContentSourceForm.php, modules/openy_gc_shared_content_server/src/SharedContentSourceListBuilder.php, modules/openy_gc_shared_content_server/src/SourceMigrationDeriver.php, src/SegmentContentAccessCheck.php
[PRODDEV-228](https://openy.atlassian.net/browse/PRODDEV-228)
```
Accept:application/json; charset=utf-8
Content-Type:application/json
x-shared-content:1
x-shared-referer:http://your.test-server.docksal
authorization:Bearer the-very-long-token
```
- Test importing content with the old API
- Test importing content with the new API
There should be no user-visible differences, but you should be able to see the change in URL with XDebug by sticking a breakpoint in SourceMigrationDeriver::getDerivativeDefinitions and running `drush cr && drush ms`. …
=> [PRODDEV-228] Rebuild shared content

modules/openy_gc_personal_training/openy_gc_personal_training.module
**Related Issue/Ticket:** 
[PRODDEV-553](https://openy.atlassian.net/browse/PRODDEV-553)
Outlined in the related issue [PRODDEV-553](https://openy.atlassian.net/browse/PRODDEV-553)
team in Slack
=> PRODDEV-553 Fix Personal training date discrepancy
