README.md
js/gated-content/package-lock.json
js/gated-content/package.json
js/gated-content/src/App.vue
js/gated-content/src/GatedContent.vue
js/gated-content/src/components/LogoutLink.vue
js/gated-content/src/components/VideoListing.vue
js/gated-content/src/components/auth/DummyAuth.vue
js/gated-content/src/main.js
js/gated-content/src/router/index.js
js/gated-content/src/store/index.js
js/gated-content/src/store/modules/auth.js
js/gated-content/src/store/modules/auth/dummy.js
js/gated-content/src/views/Home.vue
js/gated-content/src/views/Login.vue
js/gated-content/src/views/NotFound.vue
templates/paragraph--gated-content.html.twig

Steps for review:
- go to the `/gated-content` page
- verify the page loads with `#/login` hash
- verify that if you try `#/` hash, you are redirected to the `#/login` 
- verify the page contains the "Login" button
- verify when the button is pressed you are redirected to `#/` route 
- verify that route renders a page with 'Sign out' link
- verify the sign-out link signs you out

[VYMCA-8] Base JS auth component

---

modules/openy_gc_auth/modules/openy_gc_auth_example/config/install/openy_gc_auth.provider.dummy.yml
modules/openy_gc_auth/modules/openy_gc_auth_example/config/install/openy_gc_auth.settings.yml
modules/openy_gc_auth/modules/openy_gc_auth_example/openy_gc_auth_example.info.yml
modules/openy_gc_auth/modules/openy_gc_auth_example/src/Plugin/GCIdentityProvider/Example.php
modules/openy_gc_auth/openy_gc_auth.info.yml
modules/openy_gc_auth/openy_gc_auth.links.menu.yml
modules/openy_gc_auth/openy_gc_auth.routing.yml
modules/openy_gc_auth/openy_gc_auth.services.yml
modules/openy_gc_auth/src/Annotation/GCIdentityProvider.php
modules/openy_gc_auth/src/Form/GCAuthSettingsForm.php
modules/openy_gc_auth/src/Form/GCIdentityProviderEditForm.php
modules/openy_gc_auth/src/GCIdentityProviderInterface.php
modules/openy_gc_auth/src/GCIdentityProviderManager.php
modules/openy_gc_auth/src/GCIdentityProviderPluginBase.php
modules/openy_gc_demo/openy_gc_demo.info.yml
openy_gated_content.info.yml
openy_gated_content.module
templates/paragraph--gated-content.html.twig

[VYMCA-5] [VYMCA-6] Authentication system: Base module and admin UI

---

js/gated-content/src/GatedContent.vue
js/gated-content/src/client/index.js
js/gated-content/src/components/VideoListing.vue
js/gated-content/src/components/VideoTeaser.vue
js/gated-content/src/components/auth/DummyAuth.vue
js/gated-content/src/router/index.js
js/gated-content/src/store/modules/auth/dummy.js
js/gated-content/src/views/Login.vue
js/gated-content/src/views/VideoPage.vue
templates/paragraph--gated-content.html.twig

[VYMCA-11] Base for the Home page and Individual Video pages

---

js/gated-content/package-lock.json
js/gated-content/package.json
js/gated-content/src/components/ReCaptcha.vue
js/gated-content/src/components/auth/CustomAuth.vue
js/gated-content/src/store/index.js
js/gated-content/src/store/modules/auth/custom.js
js/gated-content/src/views/Login.vue
modules/openy_gc_auth/modules/openy_gc_auth_custom/README.md
modules/openy_gc_auth/modules/openy_gc_auth_custom/config/install/migrate_plus.migration.gc_auth_custom_users.yml
modules/openy_gc_auth/modules/openy_gc_auth_custom/config/install/migrate_plus.migration_group.gc_auth.yml
modules/openy_gc_auth/modules/openy_gc_auth_custom/config/install/openy_gc_auth.provider.custom.yml
modules/openy_gc_auth/modules/openy_gc_auth_custom/config/install/rest.resource.openy_gc_auth_custom.yml
modules/openy_gc_auth/modules/openy_gc_auth_custom/openy_gc_auth_custom.info.yml
modules/openy_gc_auth/modules/openy_gc_auth_custom/openy_gc_auth_custom.install
modules/openy_gc_auth/modules/openy_gc_auth_custom/openy_gc_auth_custom.module
modules/openy_gc_auth/modules/openy_gc_auth_custom/openy_gc_auth_custom.routing.yml
modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Entity/AuthCustomUser.php
modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Entity/AuthCustomUserInterface.php
modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Form/ImportCsvForm.php
modules/openy_gc_auth/modules/openy_gc_auth_custom/src/ImportCsvBatch.php
modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Plugin/GCIdentityProvider/Custom.php
modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Plugin/migrate/source/CSVLimit.php
modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Plugin/rest/resource/GatedContentCustomAuthentication.php
modules/openy_gc_auth/modules/openy_gc_auth_example/config/install/openy_gc_auth.settings.yml
modules/openy_gc_demo/openy_gc_demo.info.yml

```csv
Member ID,Member First Name,Primary Member,Member Email,Package Name,Package Site
309302,Test,Yes,TEST@GMAIL.COM,OLY - Family - Staff,Oscar Lasko Branch
309303,Jon,No,JON@GMAIL.COM,OLY - Family - Staff,Oscar Lasko Branch
117892,Doe,Yes,Doe@GMAIL.COM,West Chester - SilverSneakers - S & PP,West Chester Branch
91896,Mike,No,SUPERMIKE@GMAIL.COM,Kennett - Family - Full,Kennett Branch
```

[VYMCA-13] CSV file auth plugin

---

js/gated-content/src/GatedContent.vue
js/gated-content/src/components/LiveStreamListing.vue
js/gated-content/src/components/LiveStreamTeaser.vue
js/gated-content/src/components/LogoutLink.vue
js/gated-content/src/components/VideoListing.vue
js/gated-content/src/components/VideoTeaser.vue
js/gated-content/src/components/auth/CustomAuth.vue
js/gated-content/src/scss/components/_video-teaser.scss
js/gated-content/src/scss/global.scss
js/gated-content/src/scss/views/_login.scss
js/gated-content/src/scss/views/_video-page.scss
js/gated-content/src/views/Home.vue
js/gated-content/src/views/LiveStreamPage.vue
js/gated-content/src/views/Login.vue
js/gated-content/src/views/VideoPage.vue
js/gated-content/vue.config.js
modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Plugin/GCIdentityProvider/Custom.php
modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Plugin/rest/resource/GatedContentCustomAuthentication.php
modules/openy_gc_storage/config/install/field_inheritance.field_inheritance.eventinstance_live_stream_instructor.yml
openy_gated_content.info.yml
openy_gated_content.libraries.yml
openy_gated_content.module

Task: https://fivejars.atlassian.net/browse/VYMCA-18

 [VYMCA-18] Add reCaptcha to login form 

---

modules/openy_gc_storage/config/install/core.entity_form_display.eventinstance.live_stream.default.yml
modules/openy_gc_storage/config/install/core.entity_form_display.eventseries.live_stream.default.yml
modules/openy_gc_storage/config/install/core.entity_form_display.node.gc_video.default.yml
modules/openy_gc_storage/config/install/core.entity_view_display.eventinstance.live_stream.default.yml
modules/openy_gc_storage/openy_gc_storage.info.yml
openy_gated_content.info.yml

[VYMCA-21] Remove dependency to openy_focal_point

---

js/gated-content/package-lock.json
js/gated-content/package.json
js/gated-content/src/client/index.js
js/gated-content/src/components/LiveStreamListing.vue
js/gated-content/src/components/LiveStreamTeaser.vue
js/gated-content/src/components/VideoListing.vue
js/gated-content/src/components/VideoTeaser.vue
js/gated-content/src/filters/index.js
js/gated-content/src/scss/components/_live-stream-listing.scss
js/gated-content/src/scss/components/_video-listing.scss
js/gated-content/src/scss/global.scss
js/gated-content/src/scss/views/_home.scss
js/gated-content/src/views/LiveStreamPage.vue
js/gated-content/src/views/VideoPage.vue
modules/openy_gc_storage/config/install/field.field.eventinstance.live_stream.field_ls_category.yml
modules/openy_gc_storage/config/install/field.field.eventinstance.live_stream.field_ls_level.yml
modules/openy_gc_storage/config/install/field.field.eventinstance.live_stream.field_ls_media.yml
modules/openy_gc_storage/config/install/field.field.eventseries.live_stream.field_ls_equipment.yml
modules/openy_gc_storage/config/install/field.field.eventseries.live_stream.field_ls_level.yml

1. 2 col videos listing on ipad
2. video listings filter and sorting using jsonapi
3. schedule date at live stream page
4. hide listing if no videos
5. padding bottom for video listings

review fixes

---

js/gated-content/.eslintrc.js
js/gated-content/src/components/CategoryTeaser.vue
js/gated-content/src/components/LiveStreamListing.vue
js/gated-content/src/components/LiveStreamTeaser.vue
js/gated-content/src/components/VideoListing.vue
js/gated-content/src/components/VideoTeaser.vue
js/gated-content/src/mixins/JsonApiCombineMixin.js
js/gated-content/src/router/index.js
js/gated-content/src/scss/views/_video-page.scss
js/gated-content/src/views/CategoryPage.vue
js/gated-content/src/views/Home.vue
js/gated-content/src/views/LiveStreamPage.vue
js/gated-content/src/views/VideoCategoriesListing.vue
js/gated-content/src/views/VideoPage.vue
modules/openy_gc_storage/config/install/core.entity_form_display.eventinstance.live_stream.default.yml
modules/openy_gc_storage/config/install/core.entity_form_display.node.gc_video.default.yml
modules/openy_gc_storage/config/install/core.entity_form_display.taxonomy_term.gc_category.default.yml
modules/openy_gc_storage/config/install/core.entity_view_display.eventinstance.live_stream.default.yml
modules/openy_gc_storage/config/install/core.entity_view_display.node.gc_video.default.yml
modules/openy_gc_storage/config/install/core.entity_view_display.node.gc_video.teaser.yml
modules/openy_gc_storage/config/install/field.field.eventinstance.live_stream.field_ls_featured.yml
modules/openy_gc_storage/config/install/field.field.node.gc_video.field_gc_video_featured.yml
modules/openy_gc_storage/config/install/field.storage.eventinstance.field_ls_featured.yml
modules/openy_gc_storage/config/install/field.storage.node.field_gc_video_featured.yml

[VYMCA-24] Add categories to application

---

js/gated-content/package-lock.json
js/gated-content/package.json
js/gated-content/src/components/CategoryTeaser.vue
js/gated-content/src/components/LiveStreamListing.vue
js/gated-content/src/components/LiveStreamTeaser.vue
js/gated-content/src/components/MediaPlayer.vue
js/gated-content/src/components/VideoListing.vue
js/gated-content/src/components/VideoTeaser.vue
js/gated-content/src/mixins/JsonApiCombineMixin.js
js/gated-content/src/scss/components/_category-teaser.scss
js/gated-content/src/scss/components/_video-teaser.scss
js/gated-content/src/views/LiveStreamPage.vue
js/gated-content/src/views/VideoPage.vue
modules/openy_gc_demo/content/file/581596f7-2afa-4be1-9662-45d4c2772d60.json
modules/openy_gc_demo/content/file/700edc95-34af-4e68-b999-ab569af3bb12.json
modules/openy_gc_demo/content/media/2f38d23b-b256-4381-b643-3adcfce2e89a.json
modules/openy_gc_demo/content/media/ccbb54fb-0929-411d-bcda-1ed74fd50676.json
modules/openy_gc_demo/content/node/a92efdba-6ba8-42ea-aff9-3efff65fe092.json
modules/openy_gc_demo/content/node/ffdb52cd-d51d-4216-ba6b-71719e15b569.json
modules/openy_gc_demo/content/taxonomy_term/0549d7ef-53a1-4ee5-aa21-0565bf57a663.json
modules/openy_gc_demo/content/taxonomy_term/31877582-6c0c-4cba-897b-98c6cccfecb3.json
modules/openy_gc_demo/content/taxonomy_term/4ca14d82-e7bb-405f-854c-0a8c53a1cca1.json
modules/openy_gc_demo/content/taxonomy_term/4d7e37a0-e5ce-46a2-be75-4a160ad17828.json
modules/openy_gc_demo/content/taxonomy_term/aefaa5cc-85d6-47e6-b836-42d705483f24.json
modules/openy_gc_demo/content/taxonomy_term/cbd959dd-ee4c-4db6-9da2-20f64ee3eb08.json

**Note:** private Vimeo videos not tested and not implemented yet

[VYMCA-27] Vimeo widget for application

---

README.md
js/gated-content/src/components/MediaPlayer.vue

[VYMCA-27] Private videos support

---

modules/openy_gc_demo/content/node/b48f9ebf-4737-4d1a-8304-d3ebb4b5e1c2.json
modules/openy_gc_demo/content/paragraph/844397f8-33c2-4a45-a3ec-bc7da4023f8d.json
modules/openy_gc_demo/content/paragraph/ef77ce1c-d8e6-4eb4-9842-cd6b8ad92cd2.json
modules/openy_gc_demo/content/taxonomy_term/049c3a61-574b-409d-b9a9-6146b2d231ff.json

[VYMCA-29] Add small banner with buttons to gated content

---

openy_gated_content.module

[VYMCA-30] Events not displayed for anonymous users

---

js/gated-content/src/components/LiveStreamListing.vue
js/gated-content/src/components/LiveStreamTeaser.vue
js/gated-content/src/components/VideoListing.vue
js/gated-content/src/views/Home.vue
js/gated-content/src/views/LiveStreamPage.vue
js/gated-content/src/views/VideoPage.vue
modules/openy_gc_storage/config/install/core.entity_form_display.eventinstance.live_stream.default.yml
modules/openy_gc_storage/config/install/core.entity_form_display.eventseries.live_stream.default.yml
modules/openy_gc_storage/config/install/core.entity_form_display.node.gc_video.default.yml
modules/openy_gc_storage/config/install/core.entity_view_display.eventinstance.live_stream.default.yml
modules/openy_gc_storage/config/install/core.entity_view_display.eventseries.live_stream.default.yml
modules/openy_gc_storage/config/install/field.field.eventinstance.live_stream.field_ls_image.yml
modules/openy_gc_storage/config/install/field.field.eventseries.live_stream.field_ls_image.yml
modules/openy_gc_storage/config/install/field.storage.eventinstance.field_ls_image.yml
modules/openy_gc_storage/config/install/field.storage.eventseries.field_ls_image.yml
modules/openy_gc_storage/config/install/field_inheritance.field_inheritance.eventinstance_live_stream_image.yml
openy_gated_content.module

[VYMCA-33] [VYMCA-36] Latest videos/events if no featured results

---

js/gated-content/src/mixins/JsonApiCombineMixin.js
js/gated-content/src/views/LiveStreamPage.vue
modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Plugin/rest/resource/GatedContentCustomAuthentication.php
modules/openy_gc_storage/config/install/core.entity_form_display.eventseries.live_stream.default.yml
modules/openy_gc_storage/config/install/core.entity_view_display.eventinstance.live_stream.default.yml
modules/openy_gc_storage/config/install/core.entity_view_display.eventseries.live_stream.default.yml
modules/openy_gc_storage/config/install/field.field.eventseries.live_stream.field_ls_equipment.yml
modules/openy_gc_storage/config/install/field.storage.eventseries.field_ls_equipment.yml
modules/openy_gc_storage/config/install/field_inheritance.field_inheritance.eventinstance_live_stream_equipment.yml

[VYMCA-26] Multiple equipment reference in event

---

openy_gated_content.module

```
Successfully saved the {NAME} event series
A total of {COUNT1} existing event instances were removed
A total of {COUNT2} event instances were created as part of this event series.
```

[VYMCA-25] Event series update

---

js/gated-content/src/components/LiveStreamListing.vue
js/gated-content/src/components/Spinner.vue
js/gated-content/src/components/VideoListing.vue
js/gated-content/src/views/LiveStreamPage.vue
js/gated-content/src/views/VideoCategoriesListing.vue
js/gated-content/src/views/VideoPage.vue
openy_gated_content.libraries.yml
openy_gated_content.module

Contains commits from https://github.com/fivejars/openy_gated_content/pull/34

[VYMCA-38] Add Spinner 

---

js/gated-content/src/views/LiveStreamPage.vue
modules/openy_gc_storage/config/install/core.entity_form_display.eventinstance.live_stream.default.yml
modules/openy_gc_storage/config/install/core.entity_form_display.eventseries.live_stream.default.yml
modules/openy_gc_storage/config/install/core.entity_form_display.node.gc_video.default.yml
modules/openy_gc_storage/config/install/core.entity_view_display.eventinstance.live_stream.default.yml
modules/openy_gc_storage/config/install/core.entity_view_display.eventseries.live_stream.default.yml
modules/openy_gc_storage/config/install/field.field.eventinstance.live_stream.field_ls_equipment.yml
modules/openy_gc_storage/config/install/field.field.eventinstance.live_stream.field_ls_host_name.yml
modules/openy_gc_storage/config/install/field.field.eventinstance.live_stream.field_ls_title.yml
modules/openy_gc_storage/config/install/field.storage.eventinstance.field_ls_equipment.yml
modules/openy_gc_storage/config/install/field.storage.eventinstance.field_ls_host_name.yml
modules/openy_gc_storage/config/install/field.storage.eventinstance.field_ls_title.yml
modules/openy_gc_storage/config/install/field_inheritance.field_inheritance.eventinstance_live_stream_equipment.yml
modules/openy_gc_storage/config/install/field_inheritance.field_inheritance.eventinstance_live_stream_host_name.yml
modules/openy_gc_storage/config/install/field_inheritance.field_inheritance.eventinstance_live_stream_instructor.yml
modules/openy_gc_storage/config/install/field_inheritance.field_inheritance.eventinstance_live_stream_title.yml

[VYMCA-40] Make all event instance fields overridable

---

js/gated-content/src/components/LiveStreamListing.vue
js/gated-content/src/components/LogoutLink.vue
js/gated-content/src/components/MediaPlayer.vue
js/gated-content/src/components/VideoListing.vue
js/gated-content/src/views/CategoryPage.vue
js/gated-content/src/views/LiveStreamPage.vue
js/gated-content/src/views/VideoPage.vue

[VYMCA-43] Make 'Sign Out' a link

---

modules/openy_gc_storage/config/install/core.entity_form_display.node.vy_blog_post.default.yml
modules/openy_gc_storage/config/install/core.entity_view_display.node.vy_blog_post.default.yml
modules/openy_gc_storage/config/install/core.entity_view_display.node.vy_blog_post.teaser.yml
modules/openy_gc_storage/config/install/field.field.node.vy_blog_post.field_vy_blog_description.yml
modules/openy_gc_storage/config/install/field.field.node.vy_blog_post.field_vy_blog_image.yml
modules/openy_gc_storage/config/install/field.storage.node.field_vy_blog_description.yml
modules/openy_gc_storage/config/install/field.storage.node.field_vy_blog_image.yml
modules/openy_gc_storage/config/install/language.content_settings.node.vy_blog_post.yml
modules/openy_gc_storage/config/install/node.type.vy_blog_post.yml
modules/openy_gc_storage/config/install/taxonomy.vocabulary.gc_category.yml
modules/openy_gc_storage/config/install/taxonomy.vocabulary.gc_equipment.yml
modules/openy_gc_storage/config/install/taxonomy.vocabulary.gc_level.yml
src/EventSubscriber/GatedContentSubscriber.php

[VYMCA-47] New content type for Blogs

---

js/gated-content/src/components/event/EventListing.vue
js/gated-content/src/components/event/EventTeaser.vue
js/gated-content/src/router/index.js
js/gated-content/src/scss/components/_event-teaser.scss
js/gated-content/src/scss/global.scss
js/gated-content/src/scss/views/_virtual-meeting-page.scss
js/gated-content/src/views/Home.vue
js/gated-content/src/views/VirtualMeetingListingPage.vue
js/gated-content/src/views/VirtualMeetingPage.vue
modules/openy_gc_storage/config/install/field_inheritance.field_inheritance.eventinstance_virtual_meeting_level.yml

[VYMCA-50][VYMCA-51] Virtual meeting page and listing

---

config/install/openy_gated_content.settings.yml
js/gated-content/package.json
js/gated-content/src/GatedContent.vue
js/gated-content/src/components/event/AddToCalendar.vue
js/gated-content/src/mixins/EventMixin.js
js/gated-content/src/scss/components/_add-to-calendar.scss
js/gated-content/src/scss/global.scss
js/gated-content/src/store/index.js
js/gated-content/src/store/modules/settings.js
js/gated-content/src/views/LiveStreamPage.vue
js/gated-content/src/views/VirtualMeetingPage.vue
modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Plugin/GCIdentityProvider/Custom.php
modules/openy_gc_auth/openy_gc_auth.links.menu.yml
modules/openy_gc_auth/openy_gc_auth.links.task.yml
modules/openy_gc_auth/openy_gc_auth.routing.yml
openy_gated_content.links.menu.yml
openy_gated_content.module
openy_gated_content.routing.yml
src/Form/GCSettingsForm.php
templates/paragraph--gated-content.html.twig

[VYMCA-45] Add to Calendar link for Live Streams and Virtual Meetings

---

js/gated-content/src/views/VideoCategoriesListing.vue
openy_gated_content.routing.yml
src/Controller/CategoriesController.php

[VYMCA-52] Hide video categories without videos

---

modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Form/ImportCsvForm.php
modules/openy_gc_auth/modules/openy_gc_auth_custom/src/ImportCsvBatch.php

Issue description from **Tom Scarborough:**
> Last week I worked on augmenting the CSV migration process for loading users for the Custom authentication provider so that bulk deletions is supported. (If users present in the system are removed from the source CSV file, these members should be deleted from the system when the users import is run.)
> Thanks everyone!  From my perspective, this functionality is a very high-priority need as we have Associations coming online now that do not use Daxko or Personify to manage membership.
```csv
Member ID,Member First Name,Primary Member,Member Email,Package Name,Package Site
309302,Test,Yes,TEST@GMAIL.COM,OLY - Family - Staff,Oscar Lasko Branch
309303,Jon,No,JON@GMAIL.COM,OLY - Family - Staff,Oscar Lasko Branch
117892,Doe,Yes,Doe@GMAIL.COM,West …
```

[VYMCA-82] Use syncSource option in UI migration

---

modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_menu_link_main.yml
modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_paragraph_small_banner.yml
modules/openy_gc_shared_content/config/update/views.view.event_series.yml
modules/openy_gc_shared_content/config/update/views.view.events.yml

Jira - https://fivejars.atlassian.net/browse/VYMCA-84
**Note:** there no hook update for views configs because this module not used by any YMCA

[VYMCA-84] Fix 404 pages for videos in blogs from menu

---

modules/openy_gc_auth/openy_gc_auth.services.yml
modules/openy_gc_auth/src/EventSubscriber/VirtualYLoginRedirect.php
modules/openy_gc_auth/src/GCUserAuthorizer.php
modules/openy_gc_storage/openy_gc_storage.install
openy_gated_content.module

Fixed default permissions for Event Instance.

---

modules/openy_gc_log/config/install/views.view.virtual_y_logs.yml
modules/openy_gc_log/openy_gc_log.install
modules/openy_gc_log/openy_gc_log.routing.yml
modules/openy_gc_log/src/Entity/LogEntity.php
modules/openy_gc_log/src/EventSubscriber/GCLogUserLoginSubscriber.php
modules/openy_gc_log/src/LogArchiver.php
modules/openy_gc_log/src/Logger.php

Add uid data to the logs

---

composer.json
modules/openy_gc_auth/modules/openy_gc_auth_custom/config/install/migrate_plus.migration.gc_auth_custom_users.yml
modules/openy_gc_auth/modules/openy_gc_auth_custom/openy_gc_auth_custom.info.yml
modules/openy_gc_auth/modules/openy_gc_auth_custom/openy_gc_auth_custom.install
modules/openy_gc_auth/modules/openy_gc_auth_custom/src/Plugin/migrate/source/CSVLimit.php

[VYMCA-100] Sync option for CSV migration from UI

---

config/install/openy_gated_content.settings.yml
modules/openy_gc_auth/src/Controller/GCAuthController.php
src/Form/GCSettingsForm.php

1) Log into the Virtual Y by any provider
2) click on Sign out
3) ensure you've been successfully logout

VY rebuild logout logic a bit

---

modules/openy_gc_auth/README.md
modules/openy_gc_auth/modules/openy_gc_auth_reclique/README.md
modules/openy_gc_auth/modules/openy_gc_auth_yusa/README.md

Added readme for new modules

---

modules/openy_gc_auth/modules/openy_gc_auth_personify/config/install/openy_gc_auth.provider.personify.yml
modules/openy_gc_auth/modules/openy_gc_auth_personify/openy_gc_auth_personify.install
modules/openy_gc_auth/modules/openy_gc_auth_personify/src/Form/VirtualYPersonifyLoginForm.php
modules/openy_gc_auth/modules/openy_gc_auth_personify/src/Plugin/GCIdentityProvider/Personify.php

1) Choose Personify provider as Auth method
2) go to / virtual-ymca
3) ensure you're not redirecting immediately to Personify login form but see "Enter virtual y" button
4) click on it and finish login process

R1.2 - Personify SSO - Issue #52: Add Login form and options to redirect

---

modules/openy_gc_log/config/install/views.view.virtual_y_logs.yml
modules/openy_gc_log/openy_gc_log.install

https://github.com/ymcatwincities/openy_gated_content/issues/72

Updated vylogs from mini pager to full pager.

---

modules/openy_gc_auth/modules/openy_gc_auth_yusa/src/Plugin/GCIdentityProvider/YUSA.php

https://3.basecamp.com/3608022/buckets/17045978/todos/3262504403
https://3.basecamp.com/3608022/buckets/17045978/todos/3262498462

Added addiittional info to the Y-USA form

---

modules/openy_gc_shared_content_server/src/SourceMigrationDeriver.php

Shared content: remaining items

---

assets/js/hash.behaviors.js
openy_gated_content.libraries.yml

This PR fixes hash errors at console log that comes due to conflict between drupal and vue router.

Added library that fixes hash errors

---

modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_node_blog.yml

https://fivejars.atlassian.net/browse/VYMCA-118

[VYMCA-118] Restore blogs images

---

modules/openy_gc_storage/config/install/field.field.eventinstance.virtual_meeting.field_vm_link.yml
modules/openy_gc_storage/config/install/field.field.eventseries.virtual_meeting.field_vm_link.yml
modules/openy_gc_storage/openy_gc_storage.install

https://github.com/ymcatwincities/openy_gated_content/issues/90

Updated zoom documents.

---

composer.json
modules/openy_gc_auth/modules/openy_gc_auth_custom/openy_gc_auth_custom.module
modules/openy_gc_auth/modules/openy_gc_auth_custom/src/MigrateBatchExecutable.php

- https://3.basecamp.com/3608022/buckets/17045978/todos/3361193397
- https://fivejars.atlassian.net/browse/VYMCA-125
```csv
Member ID,Member First Name,Primary Member,Member Email,Package Name,Package Site
111797,Carol,Yes,carol@test.com,West Chester - Senior - Full,West Chester Branch
111800,Charles,Yes,charles@test.com,Jennersville - Adult - Full,Jennersville Branch
111502,Steve,No,steve@test.com,West Chester - Family - Full,West Chester Branch
```
```csv
Member ID,Member First Name,Primary Member,Member Email,Package Name,Package Site
111800,Charles,Yes,charles@test.com,Jennersville - Adult - Full,Jennersville Branch
111502,Steve,No,steve@test.com,West Chester - Family - Full,West Chester Branch
```

[VYMCA-125] Delete hard dependency to migrate_tools:5.0

---

src/Controller/CategoriesController.php
src/GCUserService.php
src/Plugin/Field/FieldWidget/GatedContentPermissionsFieldWidget.php
src/SegmentContentAccessCheck.php

https://3.basecamp.com/3608022/buckets/17045978/todos/3332684892

[VYMCA-126] Fix access checks and returned categories array

---

modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/config/install/openy_gc_auth.provider.daxko_sso.yml
modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/config/openy_gc_auth.provider.daxko_sso.yml
modules/openy_gc_log/src/LogArchiver.php

Daxko sso initial config wasnt stored under install folder.
This PR fixes it.
team in Slack

Daxko install fix

---

modules/openy_gc_log/src/LogArchiver.php

Resolves https://github.com/ymcatwincities/openy_gated_content/issues/96
team in Slack

Add null checks for entity on log archiver.

---

modules/openy_gc_auth/modules/openy_gc_auth_daxko_barcode/src/Controller/DaxkoBarcodeController.php

Use the LoggerChannelFactoryInterface instead of exact LoggerChannelFactory in the DaxkoBarcodeController

---

README.md

Update README.md - server requirements

---

modules/openy_gc_shared_content/src/Form/SharedContentFetchForm.php
modules/openy_gc_shared_content/src/Plugin/SharedContentSourceType/VirtualYVideo.php
modules/openy_gc_shared_content/src/SharedContentSourceTypeBase.php
modules/openy_gc_shared_content/templates/openy-gc-shared-content--gc-video.html.twig

- Jira [FJ] - https://fivejars.atlassian.net/browse/VYMCA-130
- Jira - https://openy.atlassian.net/browse/PRODDEV-220
- Issue - https://github.com/ymcatwincities/openy_gated_content/issues/97
There an error during the AJAX request:
> An unrecoverable error occurred. The uploaded file likely exceeded the maximum file size (500 MB) that this server supports.
This related to drupal form API:
```php
if ($ajax_form_request && !$request->request->has('form_id')) {
throw new BrokenPostRequestException($this->getFileUploadMaxSize());
}
```
The proposed solution - remove ajax from the pager.

[VYMCA-130] Fix pager in shared content

---

modules/openy_gc_auth/modules/openy_gc_auth_daxko_barcode/openy_gc_auth_daxko_barcode.install
modules/openy_gc_auth/modules/openy_gc_auth_daxko_barcode/src/Controller/DaxkoBarcodeController.php
modules/openy_gc_auth/modules/openy_gc_auth_daxko_barcode/src/Form/VirtualYDaxkoBarcodeLoginForm.php
modules/openy_gc_auth/modules/openy_gc_auth_daxko_barcode/src/Plugin/GCIdentityProvider/DaxkoBarcode.php
modules/openy_gc_auth/modules/openy_gc_auth_daxko_sso/openy_gc_auth_daxko_sso.install
src/Plugin/Field/FieldWidget/GatedContentPermissionsFieldWidget.php

https://github.com/ymcatwincities/openy_gated_content/issues/110
team in Slack

1.2.3 Minor pre release fixes.

---

modules/openy_gc_personal_training/README.md
modules/openy_gc_personal_training/openy_gc_personal_training.info.yml
modules/openy_gc_personal_training/src/Entity/PersonalTraining.php

https://openy.atlassian.net/browse/PRODDEV-194
team in Slack

[PRODDEV-194] Doc about Personal training structure

---

modules/openy_gc_shared_content_server/src/SourceMigrationDeriver.php

Fixed shared server checks

---

modules/openy_gc_auth/modules/openy_gc_auth_custom/openy_gc_auth_custom.install

https://github.com/ymcatwincities/openy_gated_content/issues/129
team in Slack

Fix config_dir in openy_gc_auth_custom_update_8009

---

modules/openy_gc_personal_training/README.md
modules/openy_gc_personal_training/openy_gc_personal_training.info.yml
modules/openy_gc_personal_training/openy_gc_personal_training.links.action.yml
modules/openy_gc_personal_training/openy_gc_personal_training.links.menu.yml
modules/openy_gc_personal_training/openy_gc_personal_training.permissions.yml
modules/openy_gc_personal_training/openy_gc_personal_training.routing.yml
modules/openy_gc_personal_training/src/Entity/PersonalTraining.php
modules/openy_gc_personal_training/src/Form/PersonalTrainingForm.php
modules/openy_gc_personal_training/src/Form/PersonalTrainingSettingsForm.php
modules/openy_gc_personal_training/src/Plugin/PersonalTrainingProvider/DefaultProvider.php

https://openy.atlassian.net/browse/PRODDEV-294
team in Slack

PRODDEV-294 Change title from Personal Training to 1on1

---

modules/openy_gc_log/src/LogArchiver.php
modules/openy_gc_personal_training/src/Controller/PeerController.php
modules/openy_gc_personal_training/src/Form/PersonalTrainingSettingsForm.php
openy_gated_content.api.php

@hamrant I was not fixing plugin methods, since you were implementing pluginable structure and could fix it better.
team in Slack

Fixed some of review comments

---

modules/openy_gc_shared_content/openy_gc_shared_content.module
modules/openy_gc_shared_content/src/Plugin/SharedContentSourceType/VirtualYBlogPost.php
modules/openy_gc_shared_content/src/Plugin/SharedContentSourceType/VirtualYVideo.php
modules/openy_gc_shared_content/src/SharedContentSourceTypeBase.php
modules/openy_gc_shared_content/templates/openy-gc-shared-content--vy-blog-post.html.twig
modules/openy_gc_shared_content_server/src/Plugin/rest/resource/SharedSourceCreate.php

https://openy.atlassian.net/browse/PRODDEV-344
team in Slack

[PRODDEV-344] Shared content improvements

---

modules/openy_gc_auth/src/GCIdentityProviderInterface.php
modules/openy_gc_auth/src/GCIdentityProviderPluginBase.php
modules/openy_gc_personal_training/config/install/openy_gc_personal_training.settings.yml
modules/openy_gc_personal_training/openy_gc_personal_training.install
modules/openy_gc_personal_training/openy_gc_personal_training.module
modules/openy_gc_personal_training/openy_gc_personal_training.routing.yml
modules/openy_gc_personal_training/src/Form/PersonalTrainingSettingsForm.php
modules/openy_gc_personal_training/src/PersonalTrainingItemsOperations.php

- https://openy.atlassian.net/browse/PRODDEV-373
- https://openy.atlassian.net/browse/PRODDEV-374
- https://openy.atlassian.net/browse/PRODDEV-391
- https://openy.atlassian.net/browse/PRODDEV-393
team in Slack

[PRODDEV-355] Cancel Session - Notifications

---

modules/openy_gc_personal_training/README.md

Readme for Cancel Sessions notifications

---

modules/openy_gc_personal_training/README.md

PRODDEV-381 - Code review comments fix

---

modules/openy_gc_auth/README.md

Added Avocado SSO note

---

composer.json

https://www.drupal.org/project/recurring_events/issues/3196702
team in Slack

Fix recurring events Event Series View

---

composer.json

https://openy.atlassian.net/browse/PRODDEV-423
team in Slack

[PRODDEV-423] Update dependencies and patches.

---

modules/openy_gc_shared_content/src/Form/SharedContentSourceServerForm.php

https://openy.atlassian.net/browse/PRODDEV-436
team in Slack

Added description

---

modules/openy_gc_log/src/Plugin/views/field/GCLogDayField.php

This PR is fix for https://github.com/ymcatwincities/openy_gated_content/issues/156
**Steps to Test:**
- Pull in the PR code.
- Clear the caches.
- Login as admin or equivalent user who can access logs and activity reports.
- Now, check the activity log and date format will be displayed in m/d/Y format.

Updated the dated from d/m/Y to m/d/Y.

---

js/gated-content/package.json

Fix for https://github.com/ymcatwincities/openy_gated_content/issues/171
team in Slack

Migrate from node-sass to sass

---

.github/pull_request_template.md

docs: Clarify merge process

---

modules/openy_gc_shared_content/README.md

No ticket, just a few spelling and grammar checks.
team in Slack

Update Shared Content Readme

---

modules/openy_gc_auth/README.md

https://openy.atlassian.net/browse/PRODDEV-463
team in Slack

[PRODDEV-463] Documentation update

---

modules/openy_gc_demo/migrations/migrate_plus.migration.virtual_y_node_video.yml

[PRODDEV-488] added duration_reference for video migration

---

modules/openy_gc_livechat/config/install/openy_gc_livechat.settings.yml
modules/openy_gc_livechat/js/chat.js
modules/openy_gc_livechat/src/Chat.php
modules/openy_gc_livechat/src/Form/LivechatForm.php
modules/openy_gc_livechat/src/Form/SettingsForm.php
modules/openy_gc_livechat/src/GCSocketServer.php
modules/openy_gc_livechat/src/Plugin/Block/LivechatBlock.php
modules/openy_gc_livechat/src/SocketServer.php

Adding https support for local and live servers.

Add https support for chats functionality

---

js/gated-content/src/components/live-chat/modal/ChatRoom.vue
js/gated-content/src/store/modules/liveChat/ratchet.js
js/gated-content/src/views/LiveStreamPage.vue

PRODDEV-509: Fixed small issues with eslint

---

modules/openy_gc_livechat/README.md
modules/openy_gc_livechat/src/Controller/LiveChatController.php

Chat logs (fix date filter)

---

assets/css/openy_carnation.css
assets/css/openy_lily.css
assets/css/openy_rose.css

 PRODDEV-540: Fixed small css problems

---

assets/css/openy_carnation.css

PRODDEV-542: Fixed problem
